# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('react-build-main-{0}', github.sha) || format('react-build-pr-{0}', github.ref)  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Cache Yarn dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('platforms/web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Rust & Cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Build
        run: make web
      - name: Typescript check
        working-directory: platforms/web
        run: yarn tsc
      - name: Lint check
        working-directory: platforms/web
        run: yarn lint
      - name: Test (with coverage!)
        working-directory: platforms/web
        run: yarn coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: platforms/web/coverage/lcov.info
          fail_ci_if_error: true
          flags: unittests-react, unittests
          # https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: |
            platforms/web/coverage
            !platforms/web/coverage/lcov-report
            !platforms/web/coverage/tmp
      - name: Install Playwright browsers
        working-directory: platforms/web
        run: npx playwright install --with-deps chromium
      - name: Browser Test
        working-directory: platforms/web
        run: yarn test:e2e
