name: Tag Release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

permissions: {}

jobs:
  tag_release:
    if: ${{ github.event.pull_request.merged == true && startsWith( github.head_ref, 'version-' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Get Version
        uses: mad9000/actions-find-and-replace-string@789e104bfa5a1e90579e74de187e696450611aa2 # 6
        id: get-version
        with:
          source: ${{ github.head_ref }}
          find: 'version-'
          replace: ''

      - name: Add Tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.PAT }}
          custom_tag: ${{steps.get-version.outputs.value}}
          tag_prefix: ''
